# packages
library(CoordinateCleaner)
library(cowplot)
library(drake)
library(ggcorrplot)
library(ggrepel)
library(haven)
library(kableExtra)
library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(plotrix)
library(rgeolocate)
library(sf)
library(tidyverse)